#pragma once

enum CONDICIONS{
  HAS_WEAPON,
  HAS_WEAPON_RANGED,
  HAS_WEAPON_MELEE,
  HAS_WEAPON_THROWN,
  WEAPON_LOADED,
  ENEMY_IN_RANGE,
  ENEMY_IN_MELEE_RANGE,
  ENEMY_IN_THROWN_RANGE,
  ENEMY_DEAD,
  AT_TARGET_LOCATION,
  DISTURBANCE_EXISTS,
  SURVEYED_AREA,
  DOOR_CLOSED,
};